// Domain-specific mock data for StitchCart
// 100% Studio-Generated Luxury Product Photography (Local Assets)

export const NAV_LINKS = [
  { label: "Collection", href: "#collection" },
  { label: "Departments", href: "#departments" },
  { label: "Experience", href: "#experience" },
  { label: "Checkout", href: "#checkout-demo" },
  { label: "Admin Suite", href: "#admin-suite" },
  { label: "Reviews", href: "#reviews" },
];

export const CATEGORIES = [
  {
    id: "blazers",
    label: "Blazers & Tailoring",
    caption: "Super 130s wools, structured shoulders & bespoke cuts",
    image: "/products/wool-atelier-suit.jpg",
    count: "42 styles",
    department: "Tailoring",
  },
  {
    id: "shirts",
    label: "Shirts & Formals",
    caption: "Egyptian cottons, pinpoint oxfords & spread collars",
    image: "/products/oxford-formal-shirt.jpg",
    count: "68 styles",
    department: "Essentials",
  },
  {
    id: "dresses",
    label: "Dresses & Skirts",
    caption: "Heavy-weight silk crepes, pleated midis & cocktail gowns",
    image: "/products/silk-crepe-dress.jpg",
    count: "54 styles",
    department: "Womenswear",
  },
  {
    id: "trousers",
    label: "Trousers & Chinos",
    caption: "Double-pleated wool trousers & tapered stretch chinos",
    image: "/products/wool-trousers.jpg",
    count: "38 styles",
    department: "Tailoring",
  },
  {
    id: "knitwear",
    label: "Fine Knitwear",
    caption: "Grade-A Mongolian cashmere & extrafine merino turtlenecks",
    image: "/products/merino-turtleneck.jpg",
    count: "29 styles",
    department: "Knitwear",
  },
  {
    id: "outerwear",
    label: "Coats & Outerwear",
    caption: "Double-breasted trench coats & camel hair overcoats",
    image: "/products/wool-trench-coat.jpg",
    count: "24 styles",
    department: "Outerwear",
  },
  {
    id: "watches",
    label: "Luxury Timepieces",
    caption: "Automatic movements, sapphire crystal & alligator leather",
    image: "/products/automatic-chronograph.jpg",
    count: "18 styles",
    department: "Horology",
  },
  {
    id: "shoes",
    label: "Shoes & Footwear",
    caption: "Handcrafted calfskin Oxfords & heritage court brogues",
    image: "/products/calfskin-brogues.jpg",
    count: "35 styles",
    department: "Footwear",
  },
];

export const BRANDS = [
  { id: "raymond", label: "Raymond Atelier", tag: "Heritage Tailoring", style: "font-serif font-semibold tracking-tight" },
  { id: "louis-philippe", label: "Louis Philippe", tag: "Upper Crest", style: "font-serif italic font-medium" },
  { id: "ralph-lauren", label: "Ralph Lauren", tag: "Purple Label", style: "font-black tracking-[0.2em]" },
  { id: "hugo-boss", label: "Hugo Boss", tag: "Black Edition", style: "font-extrabold tracking-widest" },
  { id: "massimo-dutti", label: "Massimo Dutti", tag: "Limited Studio", style: "font-light tracking-[0.24em]" },
  { id: "armani", label: "Armani Exchange", tag: "Contemporary", style: "italic font-serif font-medium" },
];

export const HERO_SLIDES = [
  {
    id: 1,
    title: "Double-Breasted Wool Atelier Suit",
    brand: "Raymond Atelier",
    category: "Blazers & Tailoring",
    price: 18999,
    originalPrice: 24999,
    rating: 4.9,
    reviews: 148,
    image: "/products/wool-atelier-suit.jpg",
    tagline: "Super 130s Merino Wool · Hand-Rolled Peak Lapels",
    badge: "Bespoke Cut",
    sku: "SC-TAILOR-081",
    inStock: true,
    fabric: "100% Italian Merino Wool",
    fit: "Tailored Structured Fit",
    color: "Midnight Charcoal Navy",
  },
  {
    id: 2,
    title: "Ivory Silk Crepe Pleated Midi",
    brand: "Massimo Dutti",
    category: "Dresses & Skirts",
    price: 16999,
    originalPrice: 21999,
    rating: 4.9,
    reviews: 192,
    image: "/products/silk-crepe-dress.jpg",
    tagline: "Pure Silk Crepe · Hand-Draped Silhouette",
    badge: "Limited Edition",
    sku: "SC-DRESS-104",
    inStock: true,
    fabric: "100% Mulberry Silk Crepe",
    fit: "Fluid Column Silhouette",
    color: "Warm Ivory",
  },
  {
    id: 3,
    title: "Ribbed Merino Turtleneck Sweater",
    brand: "Ralph Lauren",
    category: "Fine Knitwear",
    price: 14499,
    originalPrice: 18999,
    rating: 4.8,
    reviews: 116,
    image: "/products/merino-turtleneck.jpg",
    tagline: "100% Extrafine Merino Wool · Ribbed Knit",
    badge: "Editor's Pick",
    sku: "SC-KNIT-044",
    inStock: true,
    fabric: "100% Extrafine Merino Wool",
    fit: "Regular Tailored Fit",
    color: "Warm Cream Oatmeal",
  },
  {
    id: 4,
    title: "Skeleton Automatic Chronograph 41mm",
    brand: "Fossil Atelier",
    category: "Luxury Timepieces",
    price: 79999,
    originalPrice: 99999,
    rating: 5.0,
    reviews: 214,
    image: "/products/automatic-chronograph.jpg",
    tagline: "Swiss Movement · Dual Sapphire Crystal · Alligator Strap",
    badge: "Masterpiece",
    sku: "SC-WATCH-002",
    inStock: true,
    fabric: "316L Stainless Steel & Alligator Leather",
    fit: "41mm Case / 20mm Lug",
    color: "Polished Silver & Cognac",
  },
];

export const DEMO_CATALOG_PRODUCTS = [
  {
    id: "p1",
    title: "Italian Wool Tailored Suit",
    brand: "Raymond Atelier",
    category: "blazers",
    categoryLabel: "Blazers & Tailoring",
    price: 18999,
    originalPrice: 24999,
    rating: 4.9,
    reviews: 148,
    badge: "Atelier Drop",
    image: "/products/wool-atelier-suit.jpg",
    material: "Super 130s Italian Wool",
    fit: "Structured Slim Cut",
    stock: 12,
  },
  {
    id: "p2",
    title: "Pinpoint Oxford Formal Shirt",
    brand: "Louis Philippe",
    category: "shirts",
    categoryLabel: "Shirts & Formals",
    price: 3999,
    originalPrice: 4999,
    rating: 4.8,
    reviews: 284,
    badge: "Bestseller",
    image: "/products/oxford-formal-shirt.jpg",
    material: "100% 2-Ply Giza Cotton",
    fit: "Tailored Spread Collar",
    stock: 45,
  },
  {
    id: "p3",
    title: "Ivory Silk Crepe Pleated Midi",
    brand: "Massimo Dutti",
    category: "dresses",
    categoryLabel: "Dresses & Skirts",
    price: 16999,
    originalPrice: 21999,
    rating: 4.9,
    reviews: 192,
    badge: "New Season",
    image: "/products/silk-crepe-dress.jpg",
    material: "100% Mulberry Silk Crepe",
    fit: "Fluid Column Silhouette",
    stock: 8,
  },
  {
    id: "p4",
    title: "Double-Pleated Wool Trousers",
    brand: "Allen Solly",
    category: "trousers",
    categoryLabel: "Trousers & Chinos",
    price: 5999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 167,
    badge: "-25% Off",
    image: "/products/wool-trousers.jpg",
    material: "Tropical Worsted Wool",
    fit: "Relaxed Tapered Leg",
    stock: 22,
  },
  {
    id: "p5",
    title: "Ribbed Merino Turtleneck",
    brand: "Ralph Lauren",
    category: "knitwear",
    categoryLabel: "Fine Knitwear",
    price: 14499,
    originalPrice: 18999,
    rating: 4.8,
    reviews: 116,
    badge: "Grade-A Merino",
    image: "/products/merino-turtleneck.jpg",
    material: "100% Extrafine Merino Wool",
    fit: "Classic Fit",
    stock: 15,
  },
  {
    id: "p6",
    title: "Skeleton Automatic Chronograph",
    brand: "Fossil Atelier",
    category: "watches",
    categoryLabel: "Luxury Timepieces",
    price: 79999,
    originalPrice: 99999,
    rating: 5.0,
    reviews: 214,
    badge: "Exclusive",
    image: "/products/automatic-chronograph.jpg",
    material: "316L Steel & Sapphire",
    fit: "41mm Case / 20mm Lug",
    stock: 5,
  },
  {
    id: "p7",
    title: "Handcrafted Calfskin Brogues",
    brand: "Raymond Atelier",
    category: "shoes",
    categoryLabel: "Shoes & Footwear",
    price: 12499,
    originalPrice: 15999,
    rating: 4.9,
    reviews: 310,
    badge: "Hand-Burnished",
    image: "/products/calfskin-brogues.jpg",
    material: "Full Grain Italian Calfskin",
    fit: "Goodyear Welted",
    stock: 18,
  },
  {
    id: "p8",
    title: "Double-Breasted Wool Trench",
    brand: "Hugo Boss",
    category: "outerwear",
    categoryLabel: "Coats & Outerwear",
    price: 34999,
    originalPrice: 42999,
    rating: 4.9,
    reviews: 88,
    badge: "Winter Edit",
    image: "/products/wool-trench-coat.jpg",
    material: "Heavy Melton Wool",
    fit: "Structured Overcoat",
    stock: 9,
  },
];

export const VALID_COUPONS = [
  {
    code: "ATELIER20",
    type: "percent",
    value: 20,
    minCart: 5000,
    description: "20% off orders above ₹5,000",
  },
  {
    code: "FESTIVE15",
    type: "fixed",
    value: 1500,
    minCart: 8000,
    description: "₹1,500 flat discount on orders above ₹8,000",
  },
  {
    code: "WELCOME10",
    type: "percent",
    value: 10,
    minCart: 2000,
    description: "10% off your first StitchCart purchase",
  },
];

export const WORKFLOW_STAGES = [
  {
    step: "01",
    title: "Curated Discovery",
    description: "Browse 8+ departments with faceted filters for brand, cut, fabric composition, and occasion. Zero catalog noise.",
    tag: "Storefront",
    metrics: "1,200+ Curated Styles with Instant Filters",
  },
  {
    step: "02",
    title: "Transparent Bag & Coupon Math",
    description: "Persistent shopping bag with instant coupon verification (fixed or percentage) and upfront GST breakdown before checkout.",
    tag: "Bag & Pricing",
    metrics: "100% Upfront Pricing · Zero Hidden Fees",
  },
  {
    step: "03",
    title: "Direct INR Payment Gateway",
    description: "Secure Checkout for domestic cards, UPI, RuPay and net banking alongside PayPal INR with instant payment confirmation.",
    tag: "Payments",
    metrics: "256-bit SSL & Bank-Grade Security",
  },
  {
    step: "04",
    title: "Pan-India Tracking & Auto-Refunds",
    description: "Real-time order state progression (Confirmed → Quality Inspection → In Shipping → Delivered) with instant cancellation.",
    tag: "Fulfillment",
    metrics: "2-4 Day Express Pan-India Delivery",
  },
];

export const ADMIN_MODULES = [
  {
    id: "catalog",
    title: "Catalog & Media Studio",
    subtitle: "Apparel Curation & Visual Management",
    description: "Curate apparel collections with granular category classifications, brand mappings, regular vs. promotional pricing, real-time inventory counts, and high-resolution imagery.",
    features: [
      "Real-time stock level synchronization",
      "Sale price calculation with automatic promotional tags",
      "High-resolution garment zoom & fabric detail optimization",
      "Instant catalog publishing to customer storefront",
    ],
    stats: [
      { label: "Active Products", value: "348" },
      { label: "Out of Stock", value: "0" },
      { label: "Sync Speed", value: "<100ms" },
    ],
  },
  {
    id: "fulfillment",
    title: "Order Fulfillment Hub",
    subtitle: "End-to-End Lifecycle Status Management",
    description: "Track all customer orders from pending authorization to final doorstep delivery. Update order states with single-click triggers and review verified shipping addresses.",
    features: [
      "Status state machine: Confirmed → Quality Check → Dispatched → Delivered",
      "Address verification with PIN code validation",
      "Automatic stock decrementation on payment capture",
      "Direct receipt generation and itemized line inspection",
    ],
    stats: [
      { label: "Pending Orders", value: "14" },
      { label: "Shipped Today", value: "48" },
      { label: "Delivery Rate", value: "99.4%" },
    ],
  },
  {
    id: "promotions",
    title: "Promotions & Coupon Engine",
    subtitle: "Configurable Campaign Discount Studio",
    description: "Create targeted marketing campaigns with flexible coupon rules: percentage or flat INR discounts, minimum cart value thresholds, redemption limits, and automatic expiration dates.",
    features: [
      "Dual discount types: Percentage (%) or Fixed Flat (₹)",
      "Cart threshold requirements to protect margins",
      "Single-use or max redemption counters",
      "Real-time server-side validation against cart totals",
    ],
    stats: [
      { label: "Active Promos", value: "3" },
      { label: "Redemptions (MTD)", value: "1,420" },
      { label: "AOV Boost", value: "+34%" },
    ],
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Vikramaditya Singhania",
    role: "Verified Buyer · Mumbai",
    garment: "Double-Breasted Wool Atelier Suit · Raymond",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=240&auto=format&fit=crop&q=85",
    quote: "The wool suit's hand-rolled lapels and shoulder drape rival custom bespoke ateliers in Savile Row. StitchCart's delivery arrived in South Mumbai within 48 hours with flawless garment bag packaging.",
    date: "February 2026",
  },
  {
    id: 2,
    name: "Ananya Deshmukh",
    role: "Verified Buyer · New Delhi",
    garment: "Ivory Silk Crepe Pleated Midi · Massimo Dutti",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&auto=format&fit=crop&q=85",
    quote: "Pure mulberry silk with real weight and drape. The transparent checkout made applying my welcome coupon completely straightforward—no surprise shipping or tax additions at the last step.",
    date: "January 2026",
  },
  {
    id: 3,
    name: "Rohan Nambiar",
    role: "Verified Buyer · Bengaluru",
    garment: "Skeleton Automatic Chronograph 41mm · Fossil Atelier",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=240&auto=format&fit=crop&q=85",
    quote: "Finding high-end automatic horology on a platform with native INR Stripe card checkout is rare in India. The order timeline kept me updated from dispatch to signed delivery.",
    date: "February 2026",
  },
];

export const PLATFORM_METRICS = [
  { value: "₹18,500", label: "Average Order Value", note: "Curated luxury tailoring & timepieces" },
  { value: "48 hrs", label: "Metro Express Dispatch", note: "Pan-India tracked logistics" },
  { value: "99.4%", label: "Fulfillment Accuracy", note: "Zero stock oversell guarantee" },
  { value: "4.9 / 5", label: "Customer Satisfaction", note: "Based on 3,100+ verified garment reviews" },
];
